# Name of your application. Used to uniquely configure containers.
service: locali-ge

# Name of the container image.
image: thibaudgg/locali-ge.csa-admin

# Deploy to these servers.
servers:
  web:
    - isle.thibaud.gg

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: locali-ge.csa-admin.org
  forward_headers: true

# Credentials for your image host.
registry:
  username: thibaudgg

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  args:
    RUBY_VERSION: <%= File.read('.ruby-version').strip %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    RACK_ENV: production
  secret:
    - WEBHOOK_SECRET
    - COCAGNE_API_TOKEN
    - LEJARDINDEMAX_API_TOKEN
    - LOCALI_API_TOKEN
    - TOUVIERE_API_TOKEN

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
#
aliases:
  logs: app logs -n 100 -f

ssh:
  user: kamal
