name: Tests

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_FROZEN: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v7

      - name: Bootstrap
        uses: jdx/mise-action@v4
        with:
          bootstrap: true
          cache_key: "{{default}}-${{ hashFiles('Gemfile.lock') }}"

      - name: Run tests
        run: mise run test
